### ISSUE TITLE
Resolve question on strings in pact-matching-ffi

### ISSUE THREAD

**Issue by alilleybrinker** [mitre/pact-reference#13]
We'd previously discussed an open question on how to use strings in the pact-matching-ffi crate. After reading a variety of sources on Rust FFI, and looking at the ways FFI is implemented for other languages which would use Rust through the C interface (Rust, Python, C++), I think the following is the best option available:

* For inputs (Rust side is only reading, not writing), pass the strings as `*const c_char`, so the Rust needs to 1) validate the pointer isn't null, 2) validate the pointed-to string is UTF-8. Error codes will be returned to signal errors if any occur.
* For outputs (Rust side is returning a Rust-allocated string), return them as `*mut c_char`, meaning the outside part of the FFI can modify the string. If that string pointer is returned to the Rust side, Rust will need to validate 1) it isn't null, and 2) the pointer-to string is UTF-8. We'd also need to provide a `string_free` function that other languages can use to have Rust free the string.

This pattern is well established in FFI, and various language's FFI systems provide a mechanism for doing this easily.

In C++, `unique_ptr` with a custom `Deleter`, as previously discussed.

In Ruby, the `AutoPointer` class in the `FFI` module.

In Python, make a class with a custom destructor.

For our existing code, this means we ought to rewrite the function `get_error_message` to return a pointed-to string which the user on the other end would need to free.

CC @asteffey @cstepanian (I don't see Dawn's account, happy to add her if she's on GitHub)

**Comment by asteffey** [comment]
@DawnJorgensen, welcome!

**Comment by asteffey** [comment]
I agree this all makes sense.

As for `*mut c_char` vs `*const c_char`.
- For what it's worth, I don't know of any cases in Pact where we need to get a string, modify it, and then use that as an input.  For the items in `MessagePact` and `Message`, we are largely either reading (during Provider tests) or writing (during Consumer tests).  The closest thing to modification I can think of would be appending items to a list (e.g., add a metadata key/value or append a new Message to an existing MessagePact).
- I had the concern for buffer overflows if we overwrite the string.  However, I guess `snprintf(str, strlen(str), "foo...")` isn't that difficult.
- A reason for `*mut c_char`: if someone sees a "const char*" in C, and the don't read the docs, they may incorrectly assume they don't need to clean it up and end up with memory leak.  If they see a `char*` they should know they need to clean it up, and if they try to use `free` (because they didn't read the docs) they'll end up with a runtime error.
- Within Rust, it looks like `CString::into_raw` and `CString::from_raw` are specifically designed for this purpose (and `into_raw` produces a `*mut c_char`).  I'm guess these are what you will be using?

**Comment by alilleybrinker** [comment]
Yeah, the `*mut c_char` comes from `CString::into_raw`. I think, as you mention, that using `*mut` over `*const` makes it clearer the caller will need to make sure to free the memory later.
