### ISSUE TITLE
Understand how Pact JVM creates, processes, and tests MessagePacts

### ISSUE THREAD

**Issue by alilleybrinker** [mitre/pact-reference#57]
We need to better understand how Pact JVM handles the `MessagePact` type before we can replicate the same in Rust.

**Comment by alilleybrinker** [comment]
@cstepanian after the meetings and investigations, what's the status here?

**Comment by cstepanian** [comment]
I've found that the MessagePact itself is very straightforward in Pact-JVM. What's special is how Pact-JVM uses annotations to make testing convenient and integrate with Gradle and JUnit.

Pact-Rust's verification capabilities for MessagePacts are less flexible and convenient, but they are present and functional:
- The message provider must expose an HTTP JSON endpoint that accepts POST requests containing metadata about the test name and Provider States.
- The message provider responds with the appropriate message data for that provider state.
- `pact_verifier_cli` is called, pointing to a Pact to test and the provider's HTTP endpoint.
- `pact_verifier_cli` runs all tests in the Pact and reports on verification success.

Notably, the HTTP provider endpoint needs to multiplex all the tests through one URL, using only the provider states to decide which test to run. Pact-JVM provides annotations for tests so that the provider state for a given test is written with the test code itself, and the logic to find the appropriate response for a given provider state is handled by Pact-JVM.

Closing this since I found what I need in order to test MessagePacts with Pact Rust.
We might need to revisit this to port those test infrastructure features to Pact Rust.
